spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movieclub
    username: root
    password: admin
  liquibase:
    contexts: prod
  config:
    import: cloud.properties
app:
  cloudinary:
    cloud-name: ${cloud_name}
    api-key: ${api_key}
    api-secret: ${api_secret}
  storage:
    image-prefix: ""